### ISSUE TITLE
Ship 3.0.0

### ISSUE THREAD

**Issue by zertosh** [substack/watchify#168]
Prerequisites to close out 2.x.x:

* [x]  Fix listeners leak in `cmd.js` (https://github.com/substack/watchify/pull/167)
* [x] Move test output to tmp dir (https://github.com/substack/watchify/pull/164)
* [x] Fix EPERM on windows (<del>https://github.com/substack/watchify/pull/165</del>https://github.com/substack/watchify/pull/169)

3.0.0 (https://github.com/substack/watchify/pull/170):

* [x] Bump chokidar to 1.0.0-rc4
* [x] Handle "ignoring" files (https://github.com/substack/watchify/issues/162)
* [x] Add some way of allowing control over `usePolling` & `interval` (https://github.com/substack/watchify/issues/162)
* [x] Do cmd.js dotfile creation in system tmp dir (https://github.com/substack/watchify/issues/140)

Wishlist:
* Some way of watching adding/removing entry files (https://github.com/substack/watchify/pull/146 and https://github.com/substack/watchify/issues/56)

**Comment by substack** [comment]
Looks like a good roadmap. Feel free to publish the release to npm when all the issues are handled.

**Comment by zertosh** [comment]
@substack How do you feel about dropping support for node 0.8.0 and adding node 0.12.0?

**Comment by zertosh** [comment]
Released! :smile:
